apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-default-web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-default-web-api
  template:
    metadata:
      labels:
        app: dotnet-default-web-api
    spec:
      containers:
        - name: dotnet-default-web-api
          image: kakoferrare/dot-net-default-web-api:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
