apiVersion: v1
kind: Service
metadata:
  name: dotnet-default-web-api
spec:
  selector:
    app: dotnet-default-web-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
